is_training: true
total_epoch: 200
save_freq: 10
batch_size: 1
in_channels: 1
out_channels: 1

dataset:
    name:
    data_loader: base_data_generator
    train_path: ''
    eval_path: ''
    test_path: ''

model:
    name:
    filter_channels: 64
    loss: lsgan_loss
    metrics: [ssim_metrics]
    checkpoint_dir: ./_checkpoint
    scheduler:
        name: linear_decay
        learning_rate: 0.001
        epoch_decay: 100



