phase: train

dataset:
    name: NF
    data_loader: gan_2d_data_generator
    train_path: '/home/yf/datas/NF/T12STIR_train.yaml' # E:/Dataset/Neurofibromatosis/t12stir_train.yaml
    eval_path: '/home/yf/datas/NF/T12STIR_eval.yaml' # E:/Dataset/Neurofibromatosis/t12stir_eval.yaml
    test_path: '/home/yf/datas/NF/T12STIR_test.yaml' # E:/Dataset/Neurofibromatosis/t12stir_test.yaml

model:
    name: pix2pix_gan
    lambda: 100.0
    metrics: [ssim_metrics,mse_metrics,psnr_metrics]
    generator:
        name: unet
        filter_channels: 64
    discriminator:
        name: patch_gan
        filter_channels: 64
    gan_loss:
        name: lsgan_loss