phase: train

dataset:
    name: NF
    data_loader: gan_2d_data_generator
    image_size: [512,256]
    train_path: '/home/yf/datas/NF/T12STIR_train.yaml' # E:/Dataset/Neurofibromatosis/t12stir_train.yaml
    test_path: '/home/yf/datas/NF/T12STIR_test.yaml' # E:/DatasetsNeurofibromatosis/t12stir_test.yaml

model:
    name: pix2pix_gan
    generator:
        name: unet