print_freq: 100
save_freq: 200
batch_size: 8
phase: train
epoch: 200
epoch_step: 100
lr: 0.0002
dataset:
    image_size: [384,1152]
    train_path: '/home/yf/datas/NF/T12STIR_train.yaml' # E:/Datasets/Neurofibromatosis/t12stir_train.yaml
    test_path: '/home/yf/datas/NF/T12STIR_test.yaml' # E:/Datasets/Neurofibromatosis/t12stir_test.yaml
model:
    name: cycle_gan
    checkpoint_dir: _checkpoint
    in_channels: 1
    out_channels: 1
    beta1: 0.5
    sample_dir: _sample


