phase: train

dataset:
    name: NF
    data_loader: gan_3d_data_generator
    image_size: [512,256,32]
    train_path: '/home/yf/datas/NF/T12STIR_train.yaml' # E:/Dataset/Neurofibromatosis/t12stir_train.yaml
    test_path: '/home/yf/datas/NF/T12STIR_test.yaml' # E:/Dataset/Neurofibromatosis/t12stir_test.yaml

model:
    name: pix2pix_gan_3d
    lambda: 100.0
    generator:
        name: unet_3d
        filter_channels: 64
    discriminator:
        name: patch_gan_3d
        filter_channels: 64
    gan_loss:
        name: lsgan_loss