phase: train

print_freq: 100
save_freq: 200

dataset:
    name:
    data_loader: gan_data_generator
    image_size: [1152,384]
    train_path: '/home/yf/datas/NF/T12STIR_train.yaml' # E:/Datasets/Neurofibromatosis/t12stir_train.yaml
    test_path: '/home/yf/datas/NF/T12STIR_test.yaml' # E:/Datasets/Neurofibromatosis/t12stir_test.yaml

model:
    name:
    epoch: 200
    batch_size: 1
    in_channels: 1
    filter_channels: 64
    out_channels: 1
    loss: lsgan_loss
    scheduler:
        name: linear_decay
        learning_rate: 0.0002
        epoch_decay: 100
    checkpoint_dir: _checkpoint


