phase: train

dataset:
    name: NF
    data_loader: gan_3d_data_generator
    image_size: [1,512,256,32]
    train_path: '/home/yf/datas/NF/T12STIR_train.yaml' # E:/Datasets/Neurofibromatosis/t12stir_train.yaml
    test_path: '/home/yf/datas/NF/T12STIR_test.yaml' # E:/Datasets/Neurofibromatosis/t12stir_test.yaml

model:
    name: pix2pix_3dgan
    generator:
        name: unet3d
    discriminator:
        name: patch_gan3d