is_training: true
total_epoch: 400
print_freq: 100
save_freq: 100
batch_size: 1
in_channels: 1
out_channels: 1

dataset:
    name: NF
    data_loader: gan_3d_data_generator
    train_path: '/home/yf/dataset/NF/train_3d_T12STIR.yaml' # E:/Dataset/Neurofibromatosis/t12stir_train.yaml
    eval_path: '/home/yf/dataset/NF/eval_3d_T12STIR.yaml' # E:/Dataset/Neurofibromatosis/t12stir_eval.yaml
    test_path: '/home/yf/dataset/NF/test_3d_T12STIR.yaml' # E:/Dataset/Neurofibromatosis/t12stir_test.yaml

model:
    name: pix2pix_gan_3d
    filter_channels: 64 # it is useless
    loss: lsgan_loss
    metrics: [ssim_metrics,mse_metrics,psnr_metrics]
    checkpoint_dir: ./_checkpoint
    scheduler:
        name: linear_decay
        learning_rate: 0.0002
        decay_epoch: 100

    lambda: 10.0
    base_patch: [64,64,4]
    generator:
        name: unet_nf_3d
        filter_channels: 64
    discriminator:
        name: patch_gan_3d
        filter_channels: 64